<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<title>The Extended Integer (XInt) Library: Exceptions and Exception-Blocking</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<!-- Generated by Doxygen 1.6.1 -->
<div class="navigation" id="top">
  <div class="tabs">
    <ul>
      <li><a href="index.html"><span>Main&nbsp;Page</span></a></li>
      <li class="current"><a href="pages.html"><span>Related&nbsp;Pages</span></a></li>
      <li><a href="namespaces.html"><span>Namespaces</span></a></li>
      <li><a href="annotated.html"><span>Classes</span></a></li>
      <li><a href="files.html"><span>Files</span></a></li>
    </ul>
  </div>
  <div class="navpath"><a class="el" href="index.html">The Extended Integer (XInt) Library</a>
  </div>
</div>
<div class="contents">


<h1><a class="anchor" id="exceptions">Exceptions and Exception-Blocking </a></h1><h2><a class="anchor" id="blocking">
Exception Blocking</a></h2>
<p>This library includes a mechanism for preventing most exceptions from being thrown. This was added to give you, the developer using the library, maximum flexibility in dealing with its functions. You can choose to deal with errors by catching exceptions or by checking returned values for error codes, on a case-by-case basis, depending on which would make for easier or more readable code.</p>
<h2><a class="anchor" id="howitworks">
How it Works</a></h2>
<p>When exceptions are blocked, any function that would normally throw a blockable exception will return a special value indicating failure instead. For functions that return an <a class="el" href="classxint_1_1integer.html" title="The extended integer class.">xint::integer</a>, this will be <a class="el" href="nan.html">the Not-a-Number value</a>; for other functions, the value will be noted in the documentation.</p>
<p>Note that, while most exceptions can be blocked, a few are unblockable, by design.</p>
<dl class="warning"><dt><b>Warning:</b></dt><dd></dd></dl>
<p>When exceptions are blocked, <em>any</em> function can return Not-a-Number under certain conditions, not just the ones listed as throwing exceptions. An insufficient-memory exception (<a class="el" href="classxint_1_1overflow__error.html" title="Exception class.">xint::overflow_error</a>), for instance, can happen nearly anywhere.</p>
<h2><a class="anchor" id="howtouse">
How to Use the Functions</a></h2>
<p>By default, the library throws exceptions when it can't complete the task you've asked it to do, and there's no other logical way to indicate an error. But when it is more convenient, most of the exceptions that the library might throw can be blocked, by holding the <a class="el" href="namespacexint.html#ad63045584f06221eb6a7581ad3091582" title="Used for the exception-blocker.">xint::token</a> object returned by the <a class="el" href="namespacexint.html#ae7e3f6afc701f6e8873a407bb418d04c" title="Temporarily prevent the library from throwing blockable exceptions.">xint::block_exceptions</a> function. Here's an example (which can be found in the <code>examples</code> subdirectory as exceptions.cpp):</p>
<div class="fragment"><pre class="fragment">
<span class="preprocessor">#include &lt;<a class="code" href="xint_8hpp.html" title="The main header file for the XInt library.">boost/xint/xint.hpp</a>&gt;</span>
<span class="preprocessor">#include &lt;ostream&gt;</span>

<span class="keywordtype">int</span> main() {
    <span class="keyword">using namespace </span>std;
    <span class="keyword">using namespace </span>boost;
    <span class="keyword">using</span> <a class="code" href="classxint_1_1integer.html" title="The extended integer class.">xint::integer</a>;

    integer n;

    <span class="comment">// It *is* possible to block exceptions multiple times, so this assert</span>
    <span class="comment">// checks to see whether they&apos;re presently allowed. It is not needed,</span>
    <span class="comment">// it&apos;s only here for demonstration purposes.</span>
    assert(<a class="code" href="namespacexint.html#ac8be41374700d89400f5ecddf0f789e3" title="Query whether exceptions are currently allowed or blocked.">xint::exceptions_allowed</a>() == <span class="keyword">true</span>);

    <span class="comment">// We&apos;ll wrap this in a try block for demonstration purposes, just to</span>
    <span class="comment">// prove that it doesn&apos;t throw an exception. You normally don&apos;t need a</span>
    <span class="comment">// try block if you&apos;re only expecting blockable exceptions.</span>
    <span class="keywordflow">try</span> {
        <span class="comment">// Create the &quot;blocker&quot; token. Until the token is destroyed, exceptions</span>
        <span class="comment">// will be blocked, except when explicitly re-enabled.</span>
        <a class="code" href="structxint_1_1detail_1_1token.html" title="An empty struct, used in xint::token.">xint::token</a> blocker=<a class="code" href="namespacexint.html#ae7e3f6afc701f6e8873a407bb418d04c" title="Temporarily prevent the library from throwing blockable exceptions.">xint::block_exceptions</a>();

        <span class="comment">// This assert is only here for demonstration purposes.</span>
        assert(<a class="code" href="namespacexint.html#ac8be41374700d89400f5ecddf0f789e3" title="Query whether exceptions are currently allowed or blocked.">xint::exceptions_allowed</a>() == <span class="keyword">false</span>);

        <span class="comment">// Call the function(s) that should be exception-blocked. The example</span>
        <span class="comment">// call tries to interpret an empty string as an integer, which would</span>
        <span class="comment">// normally throw an xint::invalid_digit exception.</span>
        n = integer(<span class="stringliteral">&quot;&quot;</span>);

        <span class="comment">// n should be Not-a-Number, because there was an error but exceptions</span>
        <span class="comment">// were blocked. This example code is fairly useless, and is only here</span>
        <span class="comment">// for demonstration purposes, but you should always test for Not-a-Number</span>
        <span class="comment">// when blocking exceptions.</span>
        <span class="keywordflow">if</span> (n.is_nan()) {
            cout &lt;&lt; <span class="stringliteral">&quot;n is Not-a-Number, do some intelligent error handling here.&quot;</span>
                &lt;&lt; endl;
        } <span class="keywordflow">else</span> {
            <span class="comment">// This example code should never get to this block, but you would</span>
            <span class="comment">// usually put the normal program flow code here.</span>
            cout &lt;&lt; <span class="stringliteral">&quot;Error, n should be Not-a-Number and it isn&apos;t!&quot;</span> &lt;&lt; endl;
        }
    } <span class="keywordflow">catch</span> (std::exception&amp; e) {
        <span class="comment">// This example code should never get to this block, because exceptions</span>
        <span class="comment">// were blocked.</span>
        cout &lt;&lt; <span class="stringliteral">&quot;Error, threw an exception when exceptions were blocked!\n&quot;</span> &lt;&lt;
            e.what() &lt;&lt; endl;
    }

    <span class="comment">// Now exceptions are re-enabled, because the blocking behavior ended when</span>
    <span class="comment">// the &quot;blocker&quot; token was destroyed at the end of the try block. Note that</span>
    <span class="comment">// this assert is not needed, it&apos;s only here for demonstration purposes.</span>
    assert(<a class="code" href="namespacexint.html#ac8be41374700d89400f5ecddf0f789e3" title="Query whether exceptions are currently allowed or blocked.">xint::exceptions_allowed</a>() == <span class="keyword">true</span>);
}
</pre></div><p>If you need to ensure that exceptions are allowed, in one of your own functions that might be called with them blocked, you can hold the <a class="el" href="namespacexint.html#ad63045584f06221eb6a7581ad3091582" title="Used for the exception-blocker.">xint::token</a> object returned by <a class="el" href="namespacexint.html#a4b5a1a791ba11bb8f158a3b56bd9723e" title="Temprarily counteract an xint::block_exceptions token to allow all exceptions.">xint::allow_exceptions</a>. It works the same way.</p>
<p><a class="el" href="namespacexint.html#ad63045584f06221eb6a7581ad3091582" title="Used for the exception-blocker.">xint::token</a> objects should always be created on the stack, so that they are guaranteed to be destroyed in reverse order. If they are not, or if they are copied elsewhere, the results are undefined. </p>
</div>
<hr size="1"/><address style="text-align: right;"><small>Generated on Tue Apr 6 01:22:08 2010 for The Extended Integer (XInt) Library by&nbsp;
<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/></a> 1.6.1 </small></address>
</body>
</html>
